export const NONE = Object.freeze({})
export const VISIBLE = Object.freeze({ visible: '' })
export const INVISIBLE = Object.freeze({ invisible: '' })
export const OPENED = Object.freeze({ opened: '' })
export const FIRST = Object.freeze({ first: '' })
export const LAST = Object.freeze({ last: '' })
